### ISSUE TITLE
Non-ASCII character '\xce' in file

### ISSUE THREAD

**Issue by murtazabasu** [theogruner/Project_RL#4]
Hello, thanks for making this repo, I tried to connect my env and run it but I get the following error,

**SyntaxError: Non-ASCII character '\xce' in file /home/at-lab/catkin_ws3/rl_pro_telu/mpo/mpo.py on line 50, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details**

Also I have noticed some other errors in `mpo.py`  which are it would be great if you can edit and optimize the code
```

for mean, target_mean, a, target_a \
                in zip(actor_mean, target_mean, actor_cholesky, target_cholesky):
            Σ = a @ a.t()
            target_Σ = target_a @ target_a.t()
            inverse = Σ.inverse()
            inner_Σ.append(torch.trace(inverse @ target_Σ)
                           - Σ.size(0)
                           + torch.log(Σ.det() / target_Σ.det()))
            inner_μ.append((mean - target_mean) @ inverse @ (mean - target_mean))
```

The **'@**' in the lines, I don't think '@' is an operator

**Comment by theogruner** [comment]
Hi,
which python version are you using? We only run our algorithms with python3 (>=3.6.5), so if you use python2, this might explain the error.

> The '@' in the lines, I don't think '@' is an operator

In PyTorch 'A @ B' is an operator for matrix multiplication and can be used like
`torch.matmul(A, B)`.
I hope this resolves all your questions.

**Comment by murtazabasu** [comment]
Hello, thank byou for the response.
Also in the multivariate normal distribution why didn't you prefer multiplying the variance with torch.diag(cholesky_vector) which would give a diagonal matrix as variance and instead of that you preferred this line 
`        cholesky = torch.stack([σ * torch.eye(self.action_shape) for σ in cholesky_vector])`
Because when I do this I get a action of 3 dimension. 
Also, why is it necessary to run a loop for `add_act` i.e. 
```
for i in range(self.M):
                        action = action_distribution.sample()
                        additional_action.append(action)
                        additional_target_q.append(self.target_critic.forward(torch.tensor(state_batch).float(),
                                                                              action).detach().numpy())
                        additional_next_q.append(self.target_critic.forward(torch.tensor(next_state_batch).float(),
                                                                            action).detach())
                        additional_q.append(self.critic.forward(torch.tensor(state_batch).float(),
                                                                action))

```                   
Because I am already having set of batc actions, states and rewards so why we need to run and append actions from the Network. The problem my action (already being a two dimensional) gives me a shape error in the `action_q` step because the `additional_action` is a 3d vector where as the `(exp_Q/Normalization)` is a 2d vector

**Comment by theogruner** [comment]
> Also in the multivariate normal distribution why didn't you prefer multiplying the variance with torch.diag(cholesky_vector) which would give a diagonal matrix as variance and instead of that you preferred this line
cholesky = torch.stack([σ * torch.eye(self.action_shape) for σ in cholesky_vector])

We use batches of states as input for the forward method of our actor, so therefore the output is a batch of nxn matrices (n is the shape of the action space) as well and hence is 3 dimensional. σ is a vector of size n and with 'torch.stack()' we generate a batch of diagonal covariance matrices.

> Also, why is it necessary to run a loop for add_act

![mpo_m_step](https://user-images.githubusercontent.com/45177092/71180156-e19c7f00-2271-11ea-8e48-b50da8d39b3b.png)

In the M-step, the policy update is carried out by maximizing the above double expectation, first with respect to the stationary distribution and second w.r.t. the policy q. For this, we need samples q for each state s from the stationary distribution which can be estimated by 
![mpo_e_step](https://user-images.githubusercontent.com/45177092/71180115-d21d3600-2271-11ea-9e0d-304b74fe5121.png).

As you can see, we require additional actions, since our critic requires state, action pairs.
I hope this explanation is comprehensible.
